name: patrimoine360
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.1
  supabase_flutter: ^2.5.0
  url_launcher: ^6.1.10
  package_info_plus: ^9.0.0
  fl_chart: ^1.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ğŸ”¹ Configuration des icÃ´nes de l'application
flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/patrimoine360.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/patrimoine360.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/patrimoine360.png
